import type { Metadata } from "next";
import { Geist, Geist_Mono, Lora } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import StartPage from "./components/start";
import ScrollToTop from "./components/backtotop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lora = Lora({
  subsets: ['latin', 'vietnamese'], // Bắt buộc có vietnamese để hiển thị dấu chuẩn
  display: 'swap',
  weight: ['400', '500', '600', '700'], // Các độ đậm nhạt bạn muốn dùng
  style: ['normal', 'italic'],          // Cho phép dùng chữ nghiêng
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="vi"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={lora.className}>
        <Header />
        <StartPage />
        <main className="relative z-10">
          {children}
        </main>
        <ScrollToTop />
        <Footer />
      </body>
    </html>
  );
}